spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/shiba
    username: shiba
  profiles:
    include: secrets

client:
  keystore: src/main/resources/shiba-keystore.jks

mnit-esb:
  url: https://test-svcs.dhs.mn.gov/WebServices/Alfresco/CreateDocument
  jaxb-context-path: org.codeforamerica.shiba.esbwsdl

sentry:
  dsn: ${SENTRY_DSN_URL}

sender-email: help@mnbenefits.org
mail-gun:
  url: "https://api.mailgun.net/v3/mail.mnbenefits.org/messages"
  api-key: ${MAILGUN_API_KEY}

submit-via-email: ${SUBMIT_VIA_EMAIL}