spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/shiba
    username: shiba

client:
  keystore: src/main/resources/shiba-keystore.jks

mnit-esb:
  url: https://test-svcs.dhs.mn.gov/WebServices/Alfresco/CreateDocument
  jaxb-context-path: org.codeforamerica.shiba.esbwsdl

sender-email: help@mnbenefits.org
security-email: security@mnbenefits.org
audit-email: help+audit@mnbenefits.org
support-email: mnbenefits@codeforamerica.org

mail-gun:
  url: "https://api.mailgun.net/v3/mail.mnbenefits.org/messages"
  api-key: ${MAILGUN_API_KEY}
  shouldCC: false

submit-via-email: false
submit-via-api: false
send-non-partner-county-alert: false

smarty-street-url: "https://us-street.api.smartystreets.com/street-address"

encryption-key: ${ENCRYPTION_KEY}
logging:
  level:
    org.apache.pdfbox.multipdf: off

server:
  servlet:
    session:
      timeout: 30s