expedited-eligibility:
  assets:
    pageName: liquidAssets
    inputName: liquidAssets
    defaultValue: 0
  income:
    pageName: thirtyDayIncome
    inputName: moneyMadeLast30Days
    defaultValue: 0
  migrantWorker:
    pageName: migrantFarmWorker
    inputName: migrantOrSeasonalFarmWorker
    required: true
  housingCosts:
    pageName: homeExpensesAmount
    inputName: homeExpensesAmount
    defaultValue: 0
  utilityExpensesSelections:
    pageName: utilityPayments
    inputName: payForUtilities
    required: true